# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.confederation.example.com:
  peer1.confederation.example.com:
  peer0.canton.example.com:
  peer1.canton.example.com:
  peer0.canton2.example.com:
  peer1.canton2.example.com:
  peer0.municipality.example.com:
  peer1.municipality.example.com:
  peer0.municipality2.example.com:
  peer1.municipality2.example.com:
  peer0.municipality3.example.com:
  peer1.municipality3.example.com:
  peer0.esp.example.com:
  peer1.esp.example.com:

networks:
  ern:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-confederation
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.confederation.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/dec23c88607eb0e9575cc84853515c153db8f2e3f2061ba62189de3dcb2cb694_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.confederation.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/dec23c88607eb0e9575cc84853515c153db8f2e3f2061ba62189de3dcb2cb694_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/confederation.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerConfederation
    networks:
      - ern

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-canton
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.canton.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ef9219159db99dafc339ba470436de34bf6087200ec5b8caffdb68234ac99c9c_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.canton.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/ef9219159db99dafc339ba470436de34bf6087200ec5b8caffdb68234ac99c9c_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/canton.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerCanton
    networks:
      - ern

  ca2:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-canton2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.canton2.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/1b3b2f515c5a72d63d5c99882c86afe055b3e2c7393678719c10070829b7f61d_sk
    ports:
      - "11054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.canton2.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/1b3b2f515c5a72d63d5c99882c86afe055b3e2c7393678719c10070829b7f61d_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/canton2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerCanton2
    networks:
      - ern

  ca3:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-municipality
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.municipality.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/5277fd6c32f5d31b4e0da9bbdace4e134c1e20375b50776a5bd5fd15ccef0d68_sk
    ports:
      - "13054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.municipality.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/5277fd6c32f5d31b4e0da9bbdace4e134c1e20375b50776a5bd5fd15ccef0d68_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/municipality.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerMunicipality
    networks:
      - ern

  ca4:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-municipality2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.municipality2.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/f49fc30fc424811b93acfa1b6c5cf8af45ace796f3a4f7de78795b15ae44badd_sk
    ports:
      - "15054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.municipality2.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/f49fc30fc424811b93acfa1b6c5cf8af45ace796f3a4f7de78795b15ae44badd_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/municipality2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerMunicipality2
    networks:
      - ern

  ca5:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-municipality3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.municipality3.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/bf5585f5d92e13e46ae105e1b5ed17af56cab2750e68f349cc66352e57f874f8_sk
    ports:
      - "17054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.municipality3.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/bf5585f5d92e13e46ae105e1b5ed17af56cab2750e68f349cc66352e57f874f8_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/municipality3.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerMunicipality3
    networks:
      - ern

  ca6:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-esp
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.esp.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/2080c66285cf9673b68672406ecbfe49d927a460c78105f4bdce0d9bf401fa70_sk
    ports:
      - "19054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.esp.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/2080c66285cf9673b68672406ecbfe49d927a460c78105f4bdce0d9bf401fa70_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/esp.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerESP
    networks:
      - ern

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - ern

  peer0.confederation.example.com:
    container_name: peer0.confederation.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.confederation.example.com
    networks:
      - ern

  peer1.confederation.example.com:
    container_name: peer1.confederation.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.confederation.example.com
    networks:
      - ern

  peer0.canton.example.com:
    container_name: peer0.canton.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.canton.example.com
    networks:
      - ern

  peer1.canton.example.com:
    container_name: peer1.canton.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.canton.example.com
    networks:
      - ern

  peer0.canton2.example.com:
    container_name: peer0.canton2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.canton2.example.com
    networks:
      - ern

  peer1.canton2.example.com:
    container_name: peer1.canton2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.canton2.example.com
    networks:
      - ern

  peer0.municipality.example.com:
    container_name: peer0.municipality.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.municipality.example.com
    networks:
      - ern

  peer1.municipality.example.com:
    container_name: peer1.municipality.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.municipality.example.com
    networks:
      - ern

  peer0.municipality2.example.com:
    container_name: peer0.municipality2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.municipality2.example.com
    networks:
      - ern

  peer1.municipality2.example.com:
    container_name: peer1.municipality2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.municipality2.example.com
    networks:
      - ern

  peer0.municipality3.example.com:
    container_name: peer0.municipality3.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.municipality3.example.com
    networks:
      - ern

  peer1.municipality3.example.com:
    container_name: peer1.municipality3.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.municipality3.example.com
    networks:
      - ern

  peer0.esp.example.com:
    container_name: peer0.esp.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.esp.example.com
    networks:
      - ern

  peer1.esp.example.com:
    container_name: peer1.esp.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.esp.example.com
    networks:
      - ern
