# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.confederation.example.com:
  peer1.confederation.example.com:
  peer0.canton.example.com:
  peer1.canton.example.com:
  peer0.canton2.example.com:
  peer1.canton2.example.com:
  peer0.municipality.example.com:
  peer1.municipality.example.com:
  peer0.municipality2.example.com:
  peer1.municipality2.example.com:
  peer0.municipality3.example.com:
  peer1.municipality3.example.com:
  peer0.esp.example.com:
  peer1.esp.example.com:

networks:
  ern:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-confederation
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.confederation.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/9eaf8823d933437823e4f140aacc06b3f8c6d6448bc043ba244bcedcd96ab744_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.confederation.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/9eaf8823d933437823e4f140aacc06b3f8c6d6448bc043ba244bcedcd96ab744_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/confederation.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerConfederation
    networks:
      - ern

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-canton
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.canton.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/43e350c58c7f2e43499232df89c90ce9fbcaebeb10b89e1f4d3e8947f18fc55f_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.canton.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/43e350c58c7f2e43499232df89c90ce9fbcaebeb10b89e1f4d3e8947f18fc55f_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/canton.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerCanton
    networks:
      - ern

  ca2:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-canton2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.canton2.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/4703a70fe6876803307e85f4eb60a52ebc1e2eeaa2b21c77461738d7a7c93760_sk
    ports:
      - "11054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.canton2.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/4703a70fe6876803307e85f4eb60a52ebc1e2eeaa2b21c77461738d7a7c93760_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/canton2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerCanton2
    networks:
      - ern

  ca3:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-municipality
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.municipality.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/716b751ce73ed58cd559f943c0d5bbe2799f5681446542bd25ce0f6377d48c28_sk
    ports:
      - "13054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.municipality.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/716b751ce73ed58cd559f943c0d5bbe2799f5681446542bd25ce0f6377d48c28_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/municipality.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerMunicipality
    networks:
      - ern

  ca4:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-municipality2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.municipality2.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/f13a2c7af18d5c4e11663388ea87377d345e6b63f6667a753f81333020f68f9d_sk
    ports:
      - "15054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.municipality2.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/f13a2c7af18d5c4e11663388ea87377d345e6b63f6667a753f81333020f68f9d_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/municipality2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerMunicipality2
    networks:
      - ern

  ca5:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-municipality3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.municipality3.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/85c71381967a30b1d0afc3ed38f9db53641959b9ae80362b8dcad68d4c05993c_sk
    ports:
      - "17054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.municipality3.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/85c71381967a30b1d0afc3ed38f9db53641959b9ae80362b8dcad68d4c05993c_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/municipality3.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerMunicipality3
    networks:
      - ern

  ca6:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-esp
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.esp.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b6b51dea3240a0b07c5c2b4e5b79ec3adf119c0e5c10a90c2329b8257117a8e4_sk
    ports:
      - "19054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.esp.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/b6b51dea3240a0b07c5c2b4e5b79ec3adf119c0e5c10a90c2329b8257117a8e4_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/esp.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerESP
    networks:
      - ern

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - ern

  peer0.confederation.example.com:
    container_name: peer0.confederation.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.confederation.example.com
    networks:
      - ern

  peer1.confederation.example.com:
    container_name: peer1.confederation.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.confederation.example.com
    networks:
      - ern

  peer0.canton.example.com:
    container_name: peer0.canton.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.canton.example.com
    networks:
      - ern

  peer1.canton.example.com:
    container_name: peer1.canton.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.canton.example.com
    networks:
      - ern

  peer0.canton2.example.com:
    container_name: peer0.canton2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.canton2.example.com
    networks:
      - ern

  peer1.canton2.example.com:
    container_name: peer1.canton2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.canton2.example.com
    networks:
      - ern

  peer0.municipality.example.com:
    container_name: peer0.municipality.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.municipality.example.com
    networks:
      - ern

  peer1.municipality.example.com:
    container_name: peer1.municipality.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.municipality.example.com
    networks:
      - ern

  peer0.municipality2.example.com:
    container_name: peer0.municipality2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.municipality2.example.com
    networks:
      - ern

  peer1.municipality2.example.com:
    container_name: peer1.municipality2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.municipality2.example.com
    networks:
      - ern

  peer0.municipality3.example.com:
    container_name: peer0.municipality3.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.municipality3.example.com
    networks:
      - ern

  peer1.municipality3.example.com:
    container_name: peer1.municipality3.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.municipality3.example.com
    networks:
      - ern

  peer0.esp.example.com:
    container_name: peer0.esp.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.esp.example.com
    networks:
      - ern

  peer1.esp.example.com:
    container_name: peer1.esp.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.esp.example.com
    networks:
      - ern
