# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.confederation.example.com:
  peer1.confederation.example.com:
  peer0.canton.example.com:
  peer1.canton.example.com:
  peer0.canton2.example.com:
  peer1.canton2.example.com:
  peer0.municipality.example.com:
  peer1.municipality.example.com:
  peer0.municipality2.example.com:
  peer1.municipality2.example.com:
  peer0.municipality3.example.com:
  peer1.municipality3.example.com:
  peer0.municipality4.example.com:
  peer1.municipality4.example.com:
  peer0.esp.example.com:
  peer1.esp.example.com:

networks:
  ern:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-confederation
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.confederation.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/d23331926786c48136faeb8c2a6675b47ad2a679d3807b33810b0328daa5ebcc_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.confederation.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/d23331926786c48136faeb8c2a6675b47ad2a679d3807b33810b0328daa5ebcc_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/confederation.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerConfederation
    networks:
      - ern

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-canton
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.canton.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/6a6f17f543dcbfb65c2546d0d13b9c6f52332a2f229215460ef745f349ad89a0_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.canton.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/6a6f17f543dcbfb65c2546d0d13b9c6f52332a2f229215460ef745f349ad89a0_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/canton.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerCanton
    networks:
      - ern

  ca2:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-canton2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.canton2.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/0e7ed96aad9953fd9be80b82b07789d87741394f460121b4f874f26c8af87710_sk
    ports:
      - "11054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.canton2.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/0e7ed96aad9953fd9be80b82b07789d87741394f460121b4f874f26c8af87710_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/canton2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerCanton2
    networks:
      - ern

  ca3:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-municipality
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.municipality.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/2dbe6595d674391d7c17bba6fc7868d63dae41f7d296b3f4c6d056788edf605d_sk
    ports:
      - "13054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.municipality.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/2dbe6595d674391d7c17bba6fc7868d63dae41f7d296b3f4c6d056788edf605d_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/municipality.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerMunicipality
    networks:
      - ern

  ca4:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-municipality2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.municipality2.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/c555e01e22d0b8b154829caada8e5ecabaa1496b999b99155afb065a80187457_sk
    ports:
      - "15054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.municipality2.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/c555e01e22d0b8b154829caada8e5ecabaa1496b999b99155afb065a80187457_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/municipality2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerMunicipality2
    networks:
      - ern

  ca5:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-municipality3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.municipality3.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/405a40610e2a805ed8674aed6ef9d7fce054c08daaae8d38ccfc15f993148c7d_sk
    ports:
      - "17054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.municipality3.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/405a40610e2a805ed8674aed6ef9d7fce054c08daaae8d38ccfc15f993148c7d_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/municipality3.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerMunicipality3
    networks:
      - ern

  ca6:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-esp
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.esp.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/4fe3d809b681fc934e27ddb1e81ae1a9c0e2cb3605d0797107016f43e2158223_sk
    ports:
      - "19054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.esp.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/4fe3d809b681fc934e27ddb1e81ae1a9c0e2cb3605d0797107016f43e2158223_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/esp.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerESP
    networks:
      - ern

  ca7:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-municipality4
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.municipality4.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA8_PRIVATE_KEY
    ports:
      - "21054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.esp.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/4fe3d809b681fc934e27ddb1e81ae1a9c0e2cb3605d0797107016f43e2158223_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/esp.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerMunicipality4
    networks:
      - ern

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - ern

  peer0.confederation.example.com:
    container_name: peer0.confederation.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.confederation.example.com
    networks:
      - ern

  peer1.confederation.example.com:
    container_name: peer1.confederation.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.confederation.example.com
    networks:
      - ern

  peer0.canton.example.com:
    container_name: peer0.canton.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.canton.example.com
    networks:
      - ern

  peer1.canton.example.com:
    container_name: peer1.canton.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.canton.example.com
    networks:
      - ern

  peer0.canton2.example.com:
    container_name: peer0.canton2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.canton2.example.com
    networks:
      - ern

  peer1.canton2.example.com:
    container_name: peer1.canton2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.canton2.example.com
    networks:
      - ern

  peer0.municipality.example.com:
    container_name: peer0.municipality.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.municipality.example.com
    networks:
      - ern

  peer1.municipality.example.com:
    container_name: peer1.municipality.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.municipality.example.com
    networks:
      - ern

  peer0.municipality2.example.com:
    container_name: peer0.municipality2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.municipality2.example.com
    networks:
      - ern

  peer1.municipality2.example.com:
    container_name: peer1.municipality2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.municipality2.example.com
    networks:
      - ern

  peer0.municipality3.example.com:
    container_name: peer0.municipality3.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.municipality3.example.com
    networks:
      - ern

  peer1.municipality3.example.com:
    container_name: peer1.municipality3.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.municipality3.example.com
    networks:
      - ern

  peer0.municipality4.example.com:
    container_name: peer0.municipality4.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.municipality4.example.com
    networks:
      - ern

  peer1.municipality4.example.com:
    container_name: peer1.municipality4.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.municipality4.example.com
    networks:
      - ern

  peer0.esp.example.com:
    container_name: peer0.esp.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.esp.example.com
    networks:
      - ern

  peer1.esp.example.com:
    container_name: peer1.esp.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.esp.example.com
    networks:
      - ern
