# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.confederation.example.com:
  peer1.confederation.example.com:
  peer0.canton.example.com:
  peer1.canton.example.com:
  peer0.canton2.example.com:
  peer1.canton2.example.com:
  peer0.municipality.example.com:
  peer1.municipality.example.com:
  peer0.municipality2.example.com:
  peer1.municipality2.example.com:
  peer0.municipality3.example.com:
  peer1.municipality3.example.com:
  peer0.municipality4.example.com:
  peer1.municipality4.example.com:
  peer0.esp.example.com:
  peer1.esp.example.com:
  peer0.sp.example.com:
  peer1.sp.example.com:

networks:
  ern:

services:

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - ern

  peer0.confederation.example.com:
    container_name: peer0.confederation.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.confederation.example.com
    networks:
      - ern

  peer1.confederation.example.com:
    container_name: peer1.confederation.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.confederation.example.com
    networks:
      - ern

  peer0.canton.example.com:
    container_name: peer0.canton.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.canton.example.com
    networks:
      - ern

  peer1.canton.example.com:
    container_name: peer1.canton.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.canton.example.com
    networks:
      - ern

  peer0.canton2.example.com:
    container_name: peer0.canton2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.canton2.example.com
    networks:
      - ern

  peer1.canton2.example.com:
    container_name: peer1.canton2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.canton2.example.com
    networks:
      - ern

  peer0.municipality.example.com:
    container_name: peer0.municipality.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.municipality.example.com
    networks:
      - ern

  peer1.municipality.example.com:
    container_name: peer1.municipality.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.municipality.example.com
    networks:
      - ern

  peer0.municipality2.example.com:
    container_name: peer0.municipality2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.municipality2.example.com
    networks:
      - ern

  peer1.municipality2.example.com:
    container_name: peer1.municipality2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.municipality2.example.com
    networks:
      - ern

  peer0.municipality3.example.com:
    container_name: peer0.municipality3.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.municipality3.example.com
    networks:
      - ern

  peer1.municipality3.example.com:
    container_name: peer1.municipality3.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.municipality3.example.com
    networks:
      - ern

  peer0.municipality4.example.com:
    container_name: peer0.municipality4.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.municipality4.example.com
    networks:
      - ern

  peer1.municipality4.example.com:
    container_name: peer1.municipality4.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.municipality4.example.com
    networks:
      - ern

  peer0.esp.example.com:
    container_name: peer0.esp.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.esp.example.com
    networks:
      - ern

  peer1.esp.example.com:
    container_name: peer1.esp.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.esp.example.com
    networks:
      - ern

  peer0.sp.example.com:
    container_name: peer0.sp.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.sp.example.com
    networks:
      - ern

  peer1.sp.example.com:
    container_name: peer1.sp.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.sp.example.com
    networks:
      - ern

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.confederation.example.com:7051
      - CORE_PEER_LOCALMSPID=ConfederationMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/confederation.example.com/peers/peer0.confederation.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/confederation.example.com/peers/peer0.confederation.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/confederation.example.com/peers/peer0.confederation.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/confederation.example.com/users/Admin@confederation.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.example.com
      - peer0.confederation.example.com
      - peer1.confederation.example.com
      - peer0.canton.example.com
      - peer1.canton.example.com
      - peer0.municipality.example.com
      - peer1.municipality.example.com
      - peer0.municipality2.example.com
      - peer1.municipality2.example.com
      - peer0.municipality3.example.com
      - peer1.municipality3.example.com
      - peer0.municipality4.example.com
      - peer1.municipality4.example.com
      - peer0.esp.example.com
      - peer1.esp.example.com
      - peer0.sp.example.com
      - peer1.sp.example.com
    networks:
      - ern
