# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.confederation.example.com:
  peer1.confederation.example.com:
  peer0.canton.example.com:
  peer1.canton.example.com:
  peer0.canton2.example.com:
  peer1.canton2.example.com:
  peer0.municipality.example.com:
  peer1.municipality.example.com:
  peer0.municipality2.example.com:
  peer1.municipality2.example.com:
  peer0.municipality3.example.com:
  peer1.municipality3.example.com:
  peer0.municipality4.example.com:
  peer1.municipality4.example.com:
  peer0.esp.example.com:
  peer1.esp.example.com:

networks:
  ern:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-confederation
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.confederation.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/22817855089ff8df07c2377ef7f66da60f26e65dca570804766975a6fa1ee05d_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.confederation.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/22817855089ff8df07c2377ef7f66da60f26e65dca570804766975a6fa1ee05d_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/confederation.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerConfederation
    networks:
      - ern

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-canton
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.canton.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/4f3f24ea37cf402a2b39aba1a1a90d449565a1a2dcb08b9876b60505f4dfb02b_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.canton.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/4f3f24ea37cf402a2b39aba1a1a90d449565a1a2dcb08b9876b60505f4dfb02b_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/canton.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerCanton
    networks:
      - ern

  ca2:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-canton2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.canton2.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/eebc9a9ea3d92770a512a583ba56b9ecdde250d4fbcadbf7c4bbb5c268da7f1c_sk
    ports:
      - "11054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.canton2.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/eebc9a9ea3d92770a512a583ba56b9ecdde250d4fbcadbf7c4bbb5c268da7f1c_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/canton2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerCanton2
    networks:
      - ern

  ca3:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-municipality
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.municipality.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/6e12e3740a1e6c0ab97b5485873f8d8ac695f13c49184f8617e7d329f50ba5a4_sk
    ports:
      - "13054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.municipality.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/6e12e3740a1e6c0ab97b5485873f8d8ac695f13c49184f8617e7d329f50ba5a4_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/municipality.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerMunicipality
    networks:
      - ern

  ca4:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-municipality2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.municipality2.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/c42994743456c52d1241910e63ffad8d51f6f1c166de6f9e43284dd58ff92f85_sk
    ports:
      - "15054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.municipality2.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/c42994743456c52d1241910e63ffad8d51f6f1c166de6f9e43284dd58ff92f85_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/municipality2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerMunicipality2
    networks:
      - ern

  ca5:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-municipality3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.municipality3.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/a1bc8b80fed56b062b9bcc63e81ec5f19c9f140e285b52e12655e72ce65b9ce9_sk
    ports:
      - "17054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.municipality3.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/a1bc8b80fed56b062b9bcc63e81ec5f19c9f140e285b52e12655e72ce65b9ce9_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/municipality3.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerMunicipality3
    networks:
      - ern

  ca6:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-esp
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.esp.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/a78a5711e67e4f2c1ef0fd3a224b0379abc870c883305dbd9ccf8677d8387ed9_sk
    ports:
      - "19054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.esp.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/a78a5711e67e4f2c1ef0fd3a224b0379abc870c883305dbd9ccf8677d8387ed9_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/esp.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerESP
    networks:
      - ern

  ca7:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-municipality4
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.municipality4.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA8_PRIVATE_KEY
    ports:
      - "21054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.esp.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/a78a5711e67e4f2c1ef0fd3a224b0379abc870c883305dbd9ccf8677d8387ed9_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/esp.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerMunicipality4
    networks:
      - ern

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - ern

  peer0.confederation.example.com:
    container_name: peer0.confederation.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.confederation.example.com
    networks:
      - ern

  peer1.confederation.example.com:
    container_name: peer1.confederation.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.confederation.example.com
    networks:
      - ern

  peer0.canton.example.com:
    container_name: peer0.canton.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.canton.example.com
    networks:
      - ern

  peer1.canton.example.com:
    container_name: peer1.canton.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.canton.example.com
    networks:
      - ern

  peer0.canton2.example.com:
    container_name: peer0.canton2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.canton2.example.com
    networks:
      - ern

  peer1.canton2.example.com:
    container_name: peer1.canton2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.canton2.example.com
    networks:
      - ern

  peer0.municipality.example.com:
    container_name: peer0.municipality.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.municipality.example.com
    networks:
      - ern

  peer1.municipality.example.com:
    container_name: peer1.municipality.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.municipality.example.com
    networks:
      - ern

  peer0.municipality2.example.com:
    container_name: peer0.municipality2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.municipality2.example.com
    networks:
      - ern

  peer1.municipality2.example.com:
    container_name: peer1.municipality2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.municipality2.example.com
    networks:
      - ern

  peer0.municipality3.example.com:
    container_name: peer0.municipality3.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.municipality3.example.com
    networks:
      - ern

  peer1.municipality3.example.com:
    container_name: peer1.municipality3.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.municipality3.example.com
    networks:
      - ern

  peer0.municipality4.example.com:
    container_name: peer0.municipality4.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.municipality4.example.com
    networks:
      - ern

  peer1.municipality4.example.com:
    container_name: peer1.municipality4.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.municipality4.example.com
    networks:
      - ern

  peer0.esp.example.com:
    container_name: peer0.esp.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.esp.example.com
    networks:
      - ern

  peer1.esp.example.com:
    container_name: peer1.esp.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.esp.example.com
    networks:
      - ern
